apiVersion: v1
kind: Secret
metadata:
  name: backend-db-secret
  namespace: pro-be
  labels:
    app: backend
    component: api
type: Opaque
data:
  # db-user: cG9zdGdyZXM= (base64 encoded 'postgres')
  # db-password: cG9zdGdyZXM= (base64 encoded 'postgres')
  db-user: cG9zdGdyZXM=
  db-password: cG9zdGdyZXM=
