---
collections:
  - name: amazon.aws
    version: ">=6.0.0"
  - name: kubernetes.core
    version: ">=2.4.0"
  - name: community.general
    version: ">=7.0.0"
  - name: community.docker
    version: ">=3.0.0"
