apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: {{ .Values.namespace }}
  labels:
    app: frontend
    component: web
spec:
  type: {{ .Values.service.type }}
  selector:
    app: frontend
    component: web
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
  sessionAffinity: None
