apiVersion: v1
kind: Secret
metadata:
  name: backend-db-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: backend
    component: api
type: Opaque
data:
  db-user: {{ .Values.secrets.db_user | b64enc }}
  db-password: {{ .Values.secrets.db_password | b64enc }}
